# Generated by Django 5.0.4 on 2024-05-23 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('narx', models.FloatField(default=0)),
                ('kod', models.IntegerField(default=0)),
                ('miqdor', models.PositiveIntegerField(default=0)),
                ('miqdor_paket', models.PositiveIntegerField(default=1)),
                ('ekish_material_olcham', models.CharField(blank=True, max_length=100, null=True)),
                ('ekish_chuqurligi', models.CharField(blank=True, max_length=100, null=True)),
                ('masofa', models.CharField(blank=True, max_length=100, null=True)),
                ('balandlik', models.CharField(blank=True, max_length=100, null=True)),
                ('mahsulot_turi', models.CharField(blank=True, max_length=255, null=True)),
                ('mamlakat', models.CharField(blank=True, max_length=100, null=True)),
                ('sovuqqa_chiqamlilik', models.CharField(blank=True, max_length=255, null=True)),
                ('kesish', models.BooleanField(default=True)),
                ('gullash_davri', models.CharField(blank=True, max_length=50, null=True)),
                ('gullash_davri_tugashi', models.CharField(blank=True, max_length=50, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
    ]
