# Generated by Django 5.0.4 on 2024-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qonish_joyi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sotib_olish_turi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
