# Generated by Django 5.0.4 on 2024-07-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_aboute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboute',
            new_name='AbouteProduct',
        ),
    ]
